### ISSUE TITLE
EURJPY 2018 file 40.csv.gz is corrupted

### ISSUE THREAD

**Issue by ArneGockeln** [fxcm/MarketData#2]
Hi there,
I tried to download the weeks 1-47 of 2018 of EURJPY, but the file 40.csv.gz is corrupted. I tried a second time to download it via cable connection instead of wifi but the same result:

```
40.csv.gz
gunzip: 40.csv.gz: unexpected end of file
gunzip: 40.csv.gz: uncompress failed
```

Just to let you know. 
Best Arne

**Comment by FXCMAPI** [comment]
we are working on it. will update you soon
