### ISSUE TITLE
con.open_trade place order at wrong price

### ISSUE THREAD

**Issue by Ulixestoitaca** [fxcm/MarketData#5]
Hello,

I am currently using API with Python 3.7
This is the flow:

1 getting data streaming in real time (DEMO account)
2 in case my indicator/s match/es the price an order is automatically placed, lets say it is EUR/USD at 1.0999
3 order is placed 
4 on my personal panel on fxcm.it the order is reported to have been placed at a different price as 1.0999

Is this normal or is it a bug?

**Comment by fxcm-dhalpert** [comment]
If you using Market order then sometimes it may have slippage (positive or negative), if you want to control the slippage please use Range order type.

**Comment by Ulixestoitaca** [comment]
In the real world this slippage is controllable?

Il 11 ott 2019 6:23 AM, Daniel Halpert <notifications@github.com> ha scritto:

If you using Market order then sometimes it may have slippage (positive or negative), if you want to control the slippage please use Range order type.

**Comment by fxcm-dhalpert** [comment]
sure, the order will be filled in your range price, if you place Range GTC it will wait for the market to reach your range price.

**Comment by FXCMAPI** [comment]
this is rest api issue, closing this thread 
please mail to api@fxcm.com if you still have issues. 
thanks
Lei
